theme: jekyll-theme-cayman
title: [csv2db]
description: [The little CSV command line loader you always wanted]
show_downloads: ["true"]
github:
  zip_url: https://github.com/csv2db/csv2db/archive/v1.3.1.zip
  tar_url: https://github.com/csv2db/csv2db/archive/v1.3.1.tar.gz
