theme: jekyll-theme-cayman
title: [csv2db]
description: [The little CSV to database command line loader you always wanted]
show_downloads: ["true"]
github:
  is_project_page: ["true"]
  zip_url: https://github.com/csv2db/csv2db/archive/v1.5.1.zip
  tar_url: https://github.com/csv2db/csv2db/archive/v1.5.1.tar.gz
